### ISSUE TITLE
选择中单模式 机器人无法选择本地开发脚本

### ISSUE THREAD

**Issue by essionwu** [bilibili/LastOrder-Dota2#7]

**Comment by essionwu** [comment]
通过powershell启动后可以选择本地开发脚本  但是对面影魔不出现，shell启动中没报错   但是游戏开始选英雄会python会报错
![123](https://user-images.githubusercontent.com/19511467/128597087-f37059d4-1193-468f-b5be-03dab0fd33bf.png)

**Comment by Passerby** [comment]
python版本是多少?

**Comment by essionwu** [comment]
3.8跟redeme文档中一致，测试只要是调用了cuda10.1 PYTHON就会在选择英雄时异常，导致ai影魔加载不了。目前卸载了cuda 可以正常运行了，游戏没那么流畅了。tensorflow2.3与py3.8在Win10不兼容？

**Comment by Passerby** [comment]
不需要cuda，这个模型cpu完全够跑
